### PR TITLE
Add feature to list view: implement yii2-grid

### PR DESCRIPTION
**Pull request by vlydev**

### CODE REVIEW

**Comment by janisto** [comment]
Thanks, I need more time to review/think about this.

**Comment by vlydev** [comment]
@janisto Hi. a long time to wait? much improvement has been done that are waiting for the PR. If you'll be a long time to think - I will have to fork admin and develop separately, which is not desirable. The separation effort is better not to do.

**Comment by vlydev** [comment]
@janisto if there is no time to be engaged in this repository - add me to collaborators and I will support it
https://help.github.com/articles/adding-collaborators-to-a-personal-repository/

**Comment by vlydev** [comment]
@janisto Business will not wait

You have several options before October 1:
1. Take PR
2. Give the right to edit the repository - I'll do the rest
3. To recognize the fact that you do not maintain a repository, and I'm announcing my fork - the main repository.

If you do not answer until October 1 - I will choose for you the third point

**Comment by janisto** [comment]
Been really busy, but finally got time to review your pull requests, which was really hard, since you added separate pull requests. You also added a lot of features/modifications to these two pull requests.

After looking at your pull requests, I really don't like all the features you are trying to add.
I'm trying to keep this simple and "kartik\grid\GridView" isn't that simple and adds a lot of extra dependencies.

What are the main reasons you would like to use "kartik\grid\GridView"?
Could those features be implemented without it?

**Comment by vlydev** [comment]
No. Main reason - editable column in list. I can add GridView class in module settings and in my project override it. If it right thing to you - im remake two PR (one - gridview class in settings, two - bulk actions) and resend them to you.

**Comment by janisto** [comment]
Ok, but send just one pull request, please.

**Comment by vlydev** [comment]
I accept decision. Im make my fork of your repo and will develop it separately. Good luck with your version

**Pull request closed without merging**
